### ISSUE TITLE
crash with PKRevealController - Bad-Access

### ISSUE THREAD

**Issue by eikebartels** [sebastienwindal/FRDLivelyButton#1]
Hey, I have a Issue with PKRevealController. 
- integrated with pod 'FRDLivelyButton', '~> 1.0.0'
- BaseViewController -->  a lot of other view controller 

I set the button in the BaseViewController in the viewdidload. 

After maybe 4-5 viewcontroller changes the app crashed.

BaseViewController

```
- (void)viewDidLoad{
 [super viewDidLoad]
// Do any additional setup after loading the view.
 if (self.revealController){
        menuBt = [[FRDLivelyButton alloc] initWithFrame:CGRectMake(0,0,36,28)];
        [menuBt setStyle:kFRDLivelyButtonStyleHamburger animated:NO];
        [menuBt addTarget:self action:@selector(menuAction:)    forControlEvents:UIControlEventTouchUpInside];

        [menuBt setOptions:@{ kFRDLivelyButtonLineWidth: @(2.0f),
                              kFRDLivelyButtonHighlightedColor: [UIColor colorWithWhite:1. alpha:0.5],
                              kFRDLivelyButtonColor: [UIColor whiteColor]
                              }];

        UIBarButtonItem *buttonItem = [[UIBarButtonItem alloc] initWithCustomView:menuBt];
        self.navigationItem.rightBarButtonItem = buttonItem;
        self.revealController.delegate = self;
    }
```

Any idea what can I do?

**Comment by fabiopelosin** [comment]
I have a similar issue which appears to be related to the button crashing if released while an animation is in progress.

**Comment by eikebartels** [comment]
Hey @irrationalfab take a look at #2

**Comment by fabiopelosin** [comment]
@eikebartels Thanks for fixing this before I even got the time to properly read the source! I can conform that the fix looks good and that the crash is effectively resolved in my situation :beers: 

@sebastienwindal Thanks for the awesome lib
