### ISSUE TITLE
Crash in modal view

### ISSUE THREAD

**Issue by kronik** [sebastienwindal/FRDLivelyButton#5]
Hi! 

I've put lively button on top right in navigation bar of modal viewconroller and added dismissViewController as a handler. And right in the moment I tap on this button crash happens. Brief analysis shows that message have been sent to deallocated instance. That happens in showUnHighlight when block is being called after dealloc. I placed this into dealloc to fix the issue:

```
[self.layer removeAllAnimations];
self.shapeLayers = nil;
```

Could you verify this issue? 

Thanks.

**Comment by sebastienwindal** [comment]
I definitively did not test this use case. Thanks for catching this.

I am going to have to give it a try but that looks like the right fix even though this thread:
http://stackoverflow.com/questions/5598768/removing-all-current-animations-when-uiview-dealloc-still-leaving-reference
and its answer:
http://stackoverflow.com/questions/1180336/will-sending-removeallanimations-to-a-layer-also-propagate-to-all-its-sublayer

makes me wonder if the removeAllAnimations should be done on all the sub-layers explicitly, not just self.layer.

**Comment by sebastienwindal** [comment]
Fixed in 1.1.3.
