### ISSUE TITLE
iOS 6.0+

### ISSUE THREAD

**Issue by LeeSanghoon** [sebastienwindal/FRDLivelyButton#7]
I think this can run on iOS 6.0.
Why did you set required version to iOS 6.1?

**Comment by sebastienwindal** [comment]
You "think" or you tried and you know it for a fact ;-)
I did not. I developed in on 7.0, someone who needed it for 6.1 actually tried and changed the version in a pull request, so this is why it is 6.1 as of now. I have no interest in trying for older versions.
